/hik_camera_ros2_driver:
  ros__parameters:
    camera_info_url: "package://hik_camera_ros2_driver/config/camera_info.yaml"
    pixel_format: "BayerRG8"        # Recommended Option: "RGB8Packed", "BayerRG8"
    adc_bit_depth: "Bits_8"         # If using "BayerRG8", <adc_bit_depth> must be set as "Bits_8"; otherwise, it can be "Bits_8" or "Bits_12"
    use_sensor_data_qos: true
    camera_name: "front"
    # frame_id: "optical_frame"     # If not set, it will be set as <camera_name>_optical_frame
    # camera_topic: "image"         # If not set, it will be set as <camera_name>/image

    camera_sn: "DA0434641" # "DA4714681"

    acquisition_frame_rate: 60.0   # Unit: Hz
    exposure_time: 5000             # Unit: us
    gain: 16.9                      # Range: 0.0 ~ 16.9, Unit: dB
